artifact_uri: file:///C:/Users/Rishabh Pandey/risp/automl-platform/automl-platform/backend/app/storage/mlflow/697986315770978318/9ad43690b0dd445db3b331d64de56b73/artifacts
end_time: 1784570625722
entry_point_name: ''
experiment_id: '697986315770978318'
lifecycle_stage: active
run_id: 9ad43690b0dd445db3b331d64de56b73
run_name: catboost
run_uuid: 9ad43690b0dd445db3b331d64de56b73
source_name: ''
source_type: 4
source_version: ''
start_time: 1784570621650
status: 3
tags: []
user_id: Rishabh Pandey
