artifact_uri: file:///C:/Users/Rishabh Pandey/risp/automl-platform/automl-platform/backend/app/storage/mlflow/697986315770978318/c794845d8b914d7d9a62f8c47bdd0c5e/artifacts
end_time: 1784571599872
entry_point_name: ''
experiment_id: '697986315770978318'
lifecycle_stage: active
run_id: c794845d8b914d7d9a62f8c47bdd0c5e
run_name: logistic_regression
run_uuid: c794845d8b914d7d9a62f8c47bdd0c5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1784571598971
status: 3
tags: []
user_id: Rishabh Pandey
